### ISSUE TITLE
action_page.php error

### ISSUE THREAD

**Issue by ChiefMedicalOfficer** [SephirothMarasov/Equipment-Fault-Tracker#3]
Received an error for an undefined variable $hostname.

I see at the top of the above file $servername. Should this be $hostname?

```
 $servername = "localhost";
 [...]
 $dbconnect=mysqli_connect($hostname,$username,$password,$db);
```

**Comment by SephirothMarasov** [comment]
Hello, 

I checked to see if it made any difference on my own build and it didn't appear to make a difference. If you are getting an error, perhaps change it to servername and let me know if that makes a difference for you.

**Comment by SephirothMarasov** [comment]
> Received an error for an undefined variable $hostname.
> 
> I see at the top of the above file $servername. Should this be $hostname?
> 
> ```
>  $servername = "localhost";
>  [...]
>  $dbconnect=mysqli_connect($hostname,$username,$password,$db);
> ```

Hello,

I checked to see if it made any difference on my own build and it didn't appear to make a difference. If you are getting an error, perhaps change it to servername and let me know if that makes a difference for you.

**Comment by ChiefMedicalOfficer** [comment]
> > Received an error for an undefined variable $hostname.
> > I see at the top of the above file $servername. Should this be $hostname?
> > ```
> >  $servername = "localhost";
> >  [...]
> >  $dbconnect=mysqli_connect($hostname,$username,$password,$db);
> > ```
> 
> Hello,
> 
> I checked to see if it made any difference on my own build and it didn't appear to make a difference. If you are getting an error, perhaps change it to servername and let me know if that makes a difference for you.

I had to change $servername to $hostname so it matched the other line then the error stopped.

**Comment by ChiefMedicalOfficer** [comment]
I'll try and replicate again tomorrow.

Thanks.

**Comment by SephirothMarasov** [comment]
> > > Received an error for an undefined variable $hostname.
> > > I see at the top of the above file $servername. Should this be $hostname?
> > > ```
> > >  $servername = "localhost";
> > >  [...]
> > >  $dbconnect=mysqli_connect($hostname,$username,$password,$db);
> > > ```
> > 
> > 
> > Hello,
> > I checked to see if it made any difference on my own build and it didn't appear to make a difference. If you are getting an error, perhaps change it to servername and let me know if that makes a difference for you.
> 
> I had to change $servername to $hostname so it matched the other line then the error stopped.

I wonder why its working for me then, hmm. I'm going to make the change since it was a resolving factor. thanks for the feedback
